In [1]:
import numpy as np


In [2]:
lst=[4,5,8,66,22,33]
arry=np.array(lst)
arry

array([ 4,  5,  8, 66, 22, 33])

In [3]:
print(type(arry))

<class 'numpy.ndarray'>


In [4]:
type(arry)

numpy.ndarray

In [5]:
arry.dtype

dtype('int32')

In [6]:
arry.ndim


1

In [7]:
arry.shape

(6,)

In [8]:
arry.itemsize

4

In [9]:
arry.nbytes

24

In [11]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4,])
print(a+b)

[11 22 33 44]


In [12]:
print(a*b)

[ 10  40  90 160]


In [13]:
print(a**b)

[     10     400   27000 2560000]


In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
print(np.arange(1,28,2))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27]


In [18]:
import time
import numpy as np

array_size=1000000
def py_version():
    t1=time.time()
    x=range(array_size)
    y=range(array_size)
    z=[  x[i]+y[i] for i in range(len(x)) ]
    return time.time()-t1

def numpy_version():
    t1=time.time()
    x=np.arange(array_size)
    y=np.arange(array_size)
    z= x+y
    return time.time()-t1

t1=py_version()
t2=numpy_version()

print("numpy in this example : "+str(t1/t2)+"faster")

print(t1,t2)




numpy in this example : 76.81705179282868faster
0.22984838485717773 0.0029921531677246094


In [19]:
distance_list=[10,25,6,30]
time_list=[0.4,0.5,2,0.5]

sp=distance_list/time_list
sp

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [22]:
distance_arr=np.array([10,25,6,30])
time_arr=np.array([0.4,0.5,2,0.5])

sp=distance_arr/time_arr
sp

array([25., 50.,  3., 60.])

In [26]:
arr_1=np.array([4,5,6,9,1,3])




In [27]:
arr_2=np.array([[4,11,22,33,44,55],
              [1,2,3,4,5,6]])

print(arr_2)

[[ 4 11 22 33 44 55]
 [ 1  2  3  4  5  6]]


In [28]:
arr_2.shape

(2, 6)

In [29]:
arr_2.dtype

dtype('int32')

In [30]:
arr_2.ndim


2

In [33]:
arr_2[0][3]

33

In [34]:
arr_2

array([[ 4, 11, 22, 33, 44, 55],
       [ 1,  2,  3,  4,  5,  6]])

In [35]:
arr_2[1][4]

5

In [36]:
arr_2[-1][-2]

5

In [40]:
arr_3=np.array([[[1,2,3,4,5,6],
               [10,20,30,40,50,60],
               [11,22,33,44,55,66]],
               
               [[1,2,3,4,5,6],
               [10,20,30,40,50,60],
               [11,22,33,44,55,66]],
               
               [[1,2,3,4,5,6],
               [10,20,30,40,50,60],
               [11,22,33,44,55,66]]])
              
              
arr_3

array([[[ 1,  2,  3,  4,  5,  6],
        [10, 20, 30, 40, 50, 60],
        [11, 22, 33, 44, 55, 66]],

       [[ 1,  2,  3,  4,  5,  6],
        [10, 20, 30, 40, 50, 60],
        [11, 22, 33, 44, 55, 66]],

       [[ 1,  2,  3,  4,  5,  6],
        [10, 20, 30, 40, 50, 60],
        [11, 22, 33, 44, 55, 66]]])

In [41]:
arr_3[1,1,3]

40

In [42]:
arr_3[2][0][4]

5

In [43]:
arr_4=[11,22,4,5,6]
arr_4[2]=22.22
arr_4

[11, 22, 22.22, 5, 6]

In [44]:
arr_5=arr_4.astype('float32')
arr_5[2]=15.22
arr_5

AttributeError: 'list' object has no attribute 'astype'

In [45]:
arr_5=arr_4.astype('float32')

AttributeError: 'list' object has no attribute 'astype'

In [46]:
arr_4=np.array([4,5,6,7,8])
arr_4[1]=14.23
arr_4

array([ 4, 14,  6,  7,  8])

In [47]:
arr_5=arr_4.astype('float32')
arr_5.dtype

dtype('float32')

In [48]:
arr_5[3]=55.28
arr_5


array([ 4.  , 14.  ,  6.  , 55.28,  8.  ], dtype=float32)